# Pre-commit configuration for GitLab Homelab
# Includes Kubernetes detection validation and code quality checks
# Author: Tyler Zervas
# License: MIT

repos:
  # Local hooks for project-specific checks
  - repo: local
    hooks:
      - id: k8s-detection-test
        name: Kubernetes Detection Test
        entry: scripts/test_detect_k8s.py
        language: python
        files: scripts/detect_k8s\.(py|sh)$
        pass_filenames: false
        always_run: false
        
      - id: k8s-detection-shell-test
        name: Kubernetes Detection Shell Test
        entry: bash scripts/test_detect_k8s.sh
        language: system
        files: scripts/detect_k8s\.sh$
        pass_filenames: false
        always_run: false
        
      - id: check-prerequisites
        name: Check Prerequisites
        entry: bash scripts/prereqs.sh --check-only --verbose
        language: system
        pass_filenames: false
        always_run: false
        
      - id: validate-k8s-detection
        name: Validate Kubernetes Detection Scripts
        entry: scripts/test_detect_k8s.sh
        language: system
        files: scripts/detect_k8s\.sh$
        pass_filenames: false
        always_run: false

  # Python code quality checks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # Shell script quality checks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-x]

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Documentation linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.yaml]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, yaml]

  # Security scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
