apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: allowed-ns
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: allowed-ns
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: allowed-ns
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "40"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    pods: "100"
