datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch-logging:9200
        database: "k8s-audit-*"
        jsonData:
          timeField: "@timestamp"
          esVersion: 7.0.0

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    audit:
      file: dashboards/audit-dashboard.json
