---
project: gitlab-homelab
version: '0.1.0'
phases:
  poc:
    infrastructure:
      kubernetes:
        distribution: k3s
        type: single-node
        features:
          - embedded_etcd
          - local_storage
          - traefik_ingress
    resources:
      minimum:
        cpu: 8
        memory: 32Gi
        storage: 500Gi
      allocation:
        gitlab:
          requests:
            cpu: "4"
            memory: "16Gi"
            storage: "200Gi"
          limits:
            cpu: "6"
            memory: "24Gi"
        monitoring:
          requests:
            cpu: "1"
            memory: "4Gi"
            storage: "50Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
        system:
          requests:
            cpu: "1"
            memory: "2Gi"
            storage: "50Gi"
    components:
      core:
        gitlab:
          deployment: helm
          features:
            - git
            - cicd
            - container_registry
            - basic_pages
        loadbalancer: metallb
        storage: local-path-provisioner
      monitoring:
        stack:
          - prometheus
          - grafana
        features:
          - resource_monitoring
          - performance_metrics
          - storage_tracking
      backup:
        trigger: manual
        type: full
        storage: local
      dns:
        access: lan_only
        configuration: hosts_file
        domain: vector-weight.local
        subdomains:
          - gitlab
          - registry
          - grafana

  mvp:
    infrastructure:
      kubernetes:
        distribution: k3s
        type: multi-node-optional
        features:
          - distributed_storage
          - cloud_support
    resources:
      limits:
        cpu: 24
        memory: 64Gi
        storage: 1Ti
    components:
      core:
        gitlab:
          features: all
        storage: distributed_optional
      monitoring:
        features:
          - comprehensive_dashboards
          - performance_monitoring
          - resource_tracking
          - energy_efficiency
          - anomaly_detection
          - security_monitoring
          - heuristics
      backup:
        schedule: monthly
        type: differential
        retention: configurable
      dns:
        domain: vector-weight.click
        provider: route53
        deployment_types:
          - self_hosted
          - cloud_aws_gcp
          - air_gapped

  production:
    infrastructure:
      kubernetes:
        distribution:
          - k3s
          - upstream
        type: multi-node
        features:
          - high_availability
          - cloud_native_storage
    resources:
      type: dynamic
      features:
        - configurable_baselines
        - dynamic_limits
    components:
      core:
        gitlab:
          features: enterprise
        storage: distributed
      monitoring:
        type: enterprise
        features:
          - custom_metrics
          - advanced_analytics
          - predictive_monitoring
          - security_dashboards
      backup:
        schedule: configurable
        features:
          - multi_site
          - point_in_time_recovery
          - verification
      dns:
        features:
          - full_automation
          - multi_domain
          - advanced_routing
          - ssl_automation

implementation:
  phase_transitions:
    features:
      - documented_upgrade_paths
      - migration_procedures
      - config_preservation
      - data_migration
  configuration:
    features:
      - version_control
      - environment_specific
      - documented_variables
      - deployment_templates
  testing:
    features:
      - comprehensive_suite
      - performance_benchmarks
      - security_testing
      - upgrade_testing
